### ISSUE TITLE
Long Scope not rendered properly on the Magnum

### ISSUE THREAD

**Issue by Igggosha** [Pinelog-Studios/AdditionalGuns#64]
When aiming, the texture starts clipping and as the result looks ugly and doesn't function.
<img width="1053" alt="Знімок екрана 2022-07-21 о 12 03 22" src="https://user-images.githubusercontent.com/108592631/180175197-03249811-6258-4317-b77f-374006ae6b59.png">
.

**Comment by Autovw** [comment]
Reminds me of #13 (similar issue, different gun)
The scope is basically too big for the gun, but we might be able to fix it.
This is also why the Ultra Long Scope hasn't been implemented yet, simply because it only works on something like the AWM...

**Comment by CasualNoLifer** [comment]
This happens when a scope is too small on a model because of the way the first person view relates to the model and size of the attachment. There will be issues like those on other models, but you aren't really intended to use a scope on a revolver, especially not a revolver that has a tactical rail on it. Lol.

Will still see about making it less egregious for a future patch. It's not high on the priorities list at the moment.

**Comment by CasualNoLifer** [comment]
Magnum sight compatibility has been removed as this issue has proven to not have a good solve. All weapons will be tested with all sights to ensure functionality to prevent this from happening again. This issue can be closed.

**Comment by Igggosha** [comment]
Eh, I guess I'll have to make funny snipper pistol setups with something else.
